### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd


# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas Data Frames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

In [2]:
school_data_complete.head()

Student ID       student_name gender grade        school_name  \
0           0       Paul Bradley      M   9th  Huang High School   
1           1       Victor Smith      M  12th  Huang High School   
2           2    Kevin Rodriguez      M  12th  Huang High School   
3           3  Dr. Richard Scott      M  12th  Huang High School   
4           4         Bonnie Ray      F   9th  Huang High School   

   reading_score  math_score  School ID      type  size   budget  
0             66          79          0  District  2917  1910635  
1             94          61          0  District  2917  1910635  
2             90          60          0  District  2917  1910635  
3             67          58          0  District  2917  1910635  
4             97          84          0  District  2917  1910635

In [3]:
# Total Number of Schools
total_num_schools = school_data_complete["school_name"].nunique()

# Total Number of Students
total_num_students = school_data_complete["Student ID"].nunique()

# Total Budget
total_budget = sum(school_data_complete["budget"].unique())

# Average Math Score
total_avg_math = round(school_data_complete["math_score"].mean(), 2)

# Average Reading Score
total_avg_read = round(school_data_complete["reading_score"].mean(), 2)

# Percent Students Passing Math 
passing_math = round(((sum(student >= 70 for student in school_data_complete["math_score"])
                       /total_num_students)*100),2)

# Percent Students Passing Reading
passing_read = round(((sum(student >= 70 for student in school_data_complete["reading_score"])
                       /total_num_students)*100),2)

# Percent Overall Passing Rate
overall_pass_rate = round((total_avg_math + total_avg_read)/2, 2)




In [4]:
# Print District Summary Dataframe
district_sum = [
                {
             "Total Schools": total_num_schools,
             "Total Students": total_num_students,
             "Total Budget": total_budget,
             "Average Math Score": total_avg_math,      
             "Average Reading Score": total_avg_read,
             "% Passing Math": passing_math,
             "% Passing Reading": passing_read,
             "% Overall Score": overall_pass_rate,      
                }
              ]
district_sum_df = pd.DataFrame(district_sum)
district_sum_df

Total Schools  Total Students  Total Budget  Average Math Score  \
0             15           39170      24649428               78.99   

   Average Reading Score  % Passing Math  % Passing Reading  % Overall Score  
0                  81.88           74.98              85.81            80.44

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)
  
* Create a dataframe to hold the above results

In [5]:
# Create base dataframe
school_sum_schools = school_data_complete[["school_name", "type", "student_name", "budget",
                                           "math_score", "reading_score"]]

# GroupBy State and Type
school_group = school_sum_schools.groupby(["school_name", "type"])

# Student totals
students=school_group["student_name"].count()

# Budget totals
budget = school_group["budget"].unique()

# Budget per Student
budget_per_student=budget/students

# Average Math Score
avg_math = round(school_group["math_score"].mean(), 2)

# Average Reading Score
avg_read = round(school_group["reading_score"].mean(), 2)

# Percent Students Passing Math 
math_pass=school_data_complete[school_data_complete['math_score'] >= 70].groupby(['school_name', "type"])["math_score"].count()
math_test=school_data_complete.groupby(['school_name', "type"])["math_score"].count()
math_percent_pass=round((math_pass/math_test)*100,2)

# Percent Students Passing Reading
read_pass=school_data_complete[school_data_complete['reading_score'] >= 70].groupby(['school_name', "type"])["reading_score"].count()
read_test=school_data_complete.groupby(['school_name', "type"])["reading_score"].count()
read_percent_pass=round((read_pass/read_test)*100,2)

# Percent Overall Passing Rate
all_pass_rate = round((read_percent_pass + math_percent_pass)/2,2)


In [6]:
school_summary_table = pd.DataFrame({"Total Students": students,
                                    "Total Budget": budget,
                                    "Per Student Budget": budget_per_student,
                                    "Average Math Score":avg_math,
                                    "Average Reading Score":avg_read,
                                    "% Passing Math":math_percent_pass,
                                    "% Passing Reading":read_percent_pass,
                                    "% Overall Passing":all_pass_rate})
school_summary_table

Total Students Total Budget  \
school_name           type                                    
Bailey High School    District            4976    [3124928]   
Cabrera High School   Charter             1858    [1081356]   
Figueroa High School  District            2949    [1884411]   
Ford High School      District            2739    [1763916]   
Griffin High School   Charter             1468     [917500]   
Hernandez High School District            4635    [3022020]   
Holden High School    Charter              427     [248087]   
Huang High School     District            2917    [1910635]   
Johnson High School   District            4761    [3094650]   
Pena High School      Charter              962     [585858]   
Rodriguez High School District            3999    [2547363]   
Shelton High School   Charter             1761    [1056600]   
Thomas High School    Charter             1635    [1043130]   
Wilson High School    Charter             2283    [1319574]   
Wright High School    Charter             1800    [1049400]   

                               Per Student Budget  Average Math Score  \
school_name           type                                              
Bailey High School    District            [628.0]               77.05   
Cabrera High School   Charter             [582.0]               83.06   
Figueroa High School  District            [639.0]               76.71   
Ford High School      District            [644.0]               77.10   
Griffin High School   Charter             [625.0]               83.35   
Hernandez High School District            [652.0]               77.29   
Holden High School    Charter             [581.0]               83.80   
Huang High School     District            [655.0]               76.63   
Johnson High School   District            [650.0]               77.07   
Pena High School      Charter             [609.0]               83.84   
Rodriguez High School District            [637.0]               76.84   
Shelton High School   Charter             [600.0]               83.36   
Thomas High School    Charter             [638.0]               83.42   
Wilson High School    Charter             [578.0]               83.27   
Wright High School    Charter             [583.0]               83.68   

                                Average Reading Score  % Passing Math  \
school_name           type                                              
Bailey High School    District                  81.03           66.68   
Cabrera High School   Charter                   83.98           94.13   
Figueroa High School  District                  81.16           65.99   
Ford High School      District                  80.75           68.31   
Griffin High School   Charter                   83.82           93.39   
Hernandez High School District                  80.93           66.75   
Holden High School    Charter                   83.81           92.51   
Huang High School     District                  81.18           65.68   
Johnson High School   District                  80.97           66.06   
Pena High School      Charter                   84.04           94.59   
Rodriguez High School District                  80.74           66.37   
Shelton High School   Charter                   83.73           93.87   
Thomas High School    Charter                   83.85           93.27   
Wilson High School    Charter                   83.99           93.87   
Wright High School    Charter                   83.96           93.33   

                                % Passing Reading  % Overall Passing  
school_name           type                                            
Bailey High School    District              81.93              74.31  
Cabrera High School   Charter               97.04              95.58  
Figueroa High School  District              80.74              73.36  
Ford High School      District              79.30              73.81  
Griffin High School   Charter               97.14 

## Top Performing Schools (By Passing Rate)

* Sort and display the top five schools in overall passing rate

In [7]:
sort_top_preforming=school_summary_table.sort_values("% Overall Passing",ascending=False)
sort_top_preforming.head()

Total Students Total Budget Per Student Budget  \
school_name         type                                                      
Cabrera High School Charter            1858    [1081356]            [582.0]   
Thomas High School  Charter            1635    [1043130]            [638.0]   
Pena High School    Charter             962     [585858]            [609.0]   
Griffin High School Charter            1468     [917500]            [625.0]   
Wilson High School  Charter            2283    [1319574]            [578.0]   

                             Average Math Score  Average Reading Score  \
school_name         type                                                 
Cabrera High School Charter               83.06                  83.98   
Thomas High School  Charter               83.42                  83.85   
Pena High School    Charter               83.84                  84.04   
Griffin High School Charter               83.35                  83.82   
Wilson High School  Charter               83.27                  83.99   

                             % Passing Math  % Passing Reading  \
school_name         type                                         
Cabrera High School Charter           94.13              97.04   
Thomas High School  Charter           93.27              97.31   
Pena High School    Charter           94.59              95.95   
Griffin High School Charter           93.39              97.14   
Wilson High School  Charter           93.87              96.54   

                             % Overall Passing  
school_name         type                        
Cabrera High School Charter              95.58  
Thomas High School  Charter              95.29  
Pena High School    Charter              95.27  
Griffin High School Charter              95.26  
Wilson High School  Charter              95.21

## Bottom Performing Schools (By Passing Rate)

* Sort and display the five worst-performing schools

In [8]:
sort_bottom_preforming=school_summary_table.sort_values("% Overall Passing")
sort_bottom_preforming.head()

Total Students Total Budget  \
school_name           type                                    
Rodriguez High School District            3999    [2547363]   
Figueroa High School  District            2949    [1884411]   
Huang High School     District            2917    [1910635]   
Johnson High School   District            4761    [3094650]   
Ford High School      District            2739    [1763916]   

                               Per Student Budget  Average Math Score  \
school_name           type                                              
Rodriguez High School District            [637.0]               76.84   
Figueroa High School  District            [639.0]               76.71   
Huang High School     District            [655.0]               76.63   
Johnson High School   District            [650.0]               77.07   
Ford High School      District            [644.0]               77.10   

                                Average Reading Score  % Passing Math  \
school_name           type                                              
Rodriguez High School District                  80.74           66.37   
Figueroa High School  District                  81.16           65.99   
Huang High School     District                  81.18           65.68   
Johnson High School   District                  80.97           66.06   
Ford High School      District                  80.75           68.31   

                                % Passing Reading  % Overall Passing  
school_name           type                                            
Rodriguez High School District              80.22              73.30  
Figueroa High School  District              80.74              73.36  
Huang High School     District              81.32              73.50  
Johnson High School   District              81.22              73.64  
Ford High School      District              79.30              73.81

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

In [9]:
# Create base dataframe
math = school_data_complete[["school_name","math_score", "grade"]]

#calc data by grade and group by school_name
math_9th=round(math[math['grade'] == "9th"].groupby('school_name')["math_score"].mean(),2)
math_10th=round(math[math['grade'] == "10th"].groupby('school_name')["math_score"].mean(),2)    
math_11th=round(math[math['grade'] == "11th"].groupby('school_name')["math_score"].mean(),2)    
math_12th=round(math[math['grade'] == "12th"].groupby('school_name')["math_score"].mean(),2)   

In [10]:
math_by_grade_table = pd.DataFrame({"9th Grade": math_9th,
                                    "10th Grade": math_10th,
                                    "11th Grade": math_11th,
                                    "12th Grade": math_12th,
                                    })
math_by_grade_table

9th Grade  10th Grade  11th Grade  12th Grade
school_name                                                         
Bailey High School         77.08       77.00       77.52       76.49
Cabrera High School        83.09       83.15       82.77       83.28
Figueroa High School       76.40       76.54       76.88       77.15
Ford High School           77.36       77.67       76.92       76.18
Griffin High School        82.04       84.23       83.84       83.36
Hernandez High School      77.44       77.34       77.14       77.19
Holden High School         83.79       83.43       85.00       82.86
Huang High School          77.03       75.91       76.45       77.23
Johnson High School        77.19       76.69       77.49       76.86
Pena High School           83.63       83.37       84.33       84.12
Rodriguez High School      76.86       76.61       76.40       77.69
Shelton High School        83.42       82.92       83.38       83.78
Thomas High School         83.59       83.09       83.50       83.50
Wilson High School         83.09       83.72       83.20       83.04
Wright High School         83.26       84.01       83.84       83.64

## Reading Score by Grade 

* Perform the same operations as above for reading scores

In [11]:
# Create base dataframe
read = school_data_complete[["school_name","reading_score", "grade"]]

#calc data by grade and group by school_name
read_9th=round(read[read['grade'] == "9th"].groupby('school_name')["reading_score"].mean(),2)
read_10th=round(read[read['grade'] == "10th"].groupby('school_name')["reading_score"].mean(),2)
read_11th=round(read[read['grade'] == "11th"].groupby('school_name')["reading_score"].mean(),2)
read_12th=round(read[read['grade'] == "12th"].groupby('school_name')["reading_score"].mean(),2)

In [12]:
read_by_grade_table = pd.DataFrame({"9th Grade": read_9th,
                                    "10th Grade": read_10th,
                                    "11th Grade": read_11th,
                                    "12th Grade": read_12th,
                                    })
read_by_grade_table

9th Grade  10th Grade  11th Grade  12th Grade
school_name                                                         
Bailey High School         81.30       80.91       80.95       80.91
Cabrera High School        83.68       84.25       83.79       84.29
Figueroa High School       81.20       81.41       80.64       81.38
Ford High School           80.63       81.26       80.40       80.66
Griffin High School        83.37       83.71       84.29       84.01
Hernandez High School      80.87       80.66       81.40       80.86
Holden High School         83.68       83.32       83.82       84.70
Huang High School          81.29       81.51       81.42       80.31
Johnson High School        81.26       80.77       80.62       81.23
Pena High School           83.81       83.61       84.34       84.59
Rodriguez High School      80.99       80.63       80.86       80.38
Shelton High School        84.12       83.44       84.37       82.78
Thomas High School         83.73       84.25       83.59       83.83
Wilson High School         83.94       84.02       83.76       84.32
Wright High School         83.83       83.81       84.16       84.07

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [13]:
# Sample bins. Feel free to create your own bins.
spending_bins = [0, 585, 615, 645, 675]
group_names = ["<$585", "$585-615", "$615-645", "$645-675"]

In [14]:
# Create dataframe
school_summary_table_wo_students=school_summary_table.drop(columns="Total Students")

# add Bin column
school_summary_table_wo_students["Spending Range"] = pd.cut(school_summary_table_wo_students["Per Student Budget"], spending_bins, labels=group_names)

# group by bin
school_spending = school_summary_table_wo_students.groupby("Spending Range")

# display data
school_spending.mean()




Average Math Score  Average Reading Score  % Passing Math  \
Spending Range                                                              
<$585                    83.452500              83.935000       93.460000   
$585-615                 83.600000              83.885000       94.230000   
$615-645                 79.078333              81.891667       75.668333   
$645-675                 76.996667              81.026667       66.163333   

                % Passing Reading  % Overall Passing  
Spending Range                                        
<$585                   96.610000          95.035000  
$585-615                95.900000          95.065000  
$615-645                86.106667          80.888333  
$645-675                81.133333          73.650000

## Scores by School Size

* Perform the same operations as above, based on school size.

In [15]:
# Sample bins. Feel free to create your own bins.
size_bins = [0, 1000, 2000, 5000]
group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

In [16]:
# Create dataframe
school_summary_table_renamed_students=school_summary_table.rename(columns={"Total Students":"Size"})

# add Bin column
school_summary_table_renamed_students["School Size"] = pd.cut(school_summary_table_renamed_students["Size"], size_bins, labels=group_names)

# Drop
school_summary_table_renamed_students=school_summary_table_renamed_students.drop(columns="Size")

# group by bin
school_size = school_summary_table_renamed_students.groupby("School Size")

# display data
school_size.mean()


Average Math Score  Average Reading Score  % Passing Math  \
School Size                                                                     
Small (<1000)                   83.820               83.92500        93.55000   
Medium (1000-2000)              83.374               83.86800        93.59800   
Large (2000-5000)               77.745               81.34375        69.96375   

                    % Passing Reading  % Overall Passing  
School Size                                               
Small (<1000)                96.10000            94.8250  
Medium (1000-2000)           96.79000            95.1920  
Large (2000-5000)            82.76625            76.3675

## Scores by School Type

* Perform the same operations as above, based on school type.

In [17]:
# Create dataframe and reset indes
school_summary_type=school_summary_table
school_summary_type = school_summary_type.reset_index()

# Remove unnecessary columns
school_summary_type=school_summary_type.drop(columns="Total Students")

# Group by Type
school_summary_type = school_summary_type.groupby("type")
school_summary_type.mean()




Average Math Score  Average Reading Score  % Passing Math  \
type                                                                  
Charter            83.472500              83.897500       93.620000   
District           76.955714              80.965714       66.548571   

          % Passing Reading  % Overall Passing  
type                                            
Charter           96.586250          95.102500  
District          80.798571          73.675714

# Observations based on the above data analysis are as follows:

1.  Charter schools outperform Disctict schools in measures of math and reading. The score gap between Charter and District math scores is approxmately twice the score gap in reading scores. 

2. There exists a compelling coloration between school size and educational outcomes: Small (< 1000 students) and mid-sized schools(1000-2000 students) have Average Overall Passing rates of 94.8% and 95.2% respectively while large schools (2000-5000 students) Overall Passing rate is 76.4%. 

3. There exists a nearly inverse relationship between spending per student and educational outcomes.  Schools with the highest Cost Per Student (645-675) have the lowest Overall Passing Rate (73.7) and Schools with the lowest Cost Per Student (>585) have one of the highest Overall Passing rates (95.0).

